// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz5Q3DuqRowSpSwzn3wTYTS-EdFJlyfqU',
    appId: '1:737218118328:web:6218dfc34db7e90a22ea4d',
    messagingSenderId: '737218118328',
    projectId: 'driver-app-3d44c',
    authDomain: 'driver-app-3d44c.firebaseapp.com',
    storageBucket: 'driver-app-3d44c.firebasestorage.app',
    measurementId: 'G-5PGZ476RBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrtd-WrIxDDcsNJCOwxho4VTg6pM70vw',
    appId: '1:737218118328:android:67468900b9b1a14122ea4d',
    messagingSenderId: '737218118328',
    projectId: 'driver-app-3d44c',
    storageBucket: 'driver-app-3d44c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0RbLtNJCvR0bwh1zs0H9MbAA_1JDLhZQ',
    appId: '1:737218118328:ios:fe6ea817d4c8c81922ea4d',
    messagingSenderId: '737218118328',
    projectId: 'driver-app-3d44c',
    storageBucket: 'driver-app-3d44c.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0RbLtNJCvR0bwh1zs0H9MbAA_1JDLhZQ',
    appId: '1:737218118328:ios:fe6ea817d4c8c81922ea4d',
    messagingSenderId: '737218118328',
    projectId: 'driver-app-3d44c',
    storageBucket: 'driver-app-3d44c.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz5Q3DuqRowSpSwzn3wTYTS-EdFJlyfqU',
    appId: '1:737218118328:web:d805b1ea708e3cb822ea4d',
    messagingSenderId: '737218118328',
    projectId: 'driver-app-3d44c',
    authDomain: 'driver-app-3d44c.firebaseapp.com',
    storageBucket: 'driver-app-3d44c.firebasestorage.app',
    measurementId: 'G-4HW548NZCR',
  );
}
